### ISSUE TITLE
Where is container-linux-config-transpiler program?

### ISSUE THREAD

**Issue by naisanza** [coreos/docs#1113] opened 2017-06-28 02:17 UTC
The [documentation](https://coreos.com/os/docs/latest/installing-to-disk.html#container-linux-configs) just refers to [container-linux-config-transpiler](https://github.com/coreos/container-linux-config-transpiler/tree/master/doc) without stating where the program is

**Comment by lucab** [comment] 2017-06-28 08:58
Closing as a duplicate of https://github.com/coreos/docs/issues/1112.

For reference, the first page you mentioned links to https://coreos.com/os/docs/latest/provisioning.html (which is the proper doc page regarding provisioning), and that one describes what `ct` is and where to download it.

But I still agree that some doc changes are needed, and left some more comments directly in #1112. Thanks for reporting!

**Closed by lucab** 2017-06-28 08:58 UTC

**Comment by naisanza** [comment] 2017-06-28 09:05
That's so much reading just to get down to `ct`! 

There should be a 15-second startup doc :)

**Comment by lucab** [comment] 2017-06-28 09:08
I agree, that's exactly my comment in https://github.com/coreos/docs/issues/1112#issuecomment-311598334.
