### ISSUE TITLE
Investigate locksmithctl maint. window improvements

### ISSUE THREAD

**Issue by robszumski** [coreos/docs#428] opened 2015-02-05 04:24 UTC
We have an example cloud-config for an update [maintenence window](https://coreos.com/docs/cluster-management/setup/update-strategies/#auto-updates-with-a-maintenance-window), but I think it could be improved.

Per discussion in #421, I think we need the timer to run at an interval during the window, so that it will retry the update if it can't get the lock at first. This would mean it would wait until the next day's window, which isn't bad, but might not be desired.

**Comment by xueshanf** [comment] 2015-02-05 05:38
Ref [#421] (https://github.com/coreos/docs/issues/421).  Our cluster has dedicated etcd servers which don't run fleetd service and dedicated workers which don't run etcd service(through unit mask in cloud-config). I think it is a similar architecture mentioned in [cluster achitectures](https://coreos.com/docs/cluster-management/setup/cluster-architectures/), for production implementation,  although  I could not tell if the "worker role" has etcd service running or not (no etcd service unit). 

The update strategy right now is "best-effort" and I am thinking to implement maintenance window. For the workers, there would be no reboot lock through locksmith because etcd is not running.  With this configuration, the auto-update does seem to happen for the workers even without a successful lock. Is there another process to control if the system should reboot after update is downloaded?

I will play with it. It looks like I could not use  "locksmithctl reboot" for workers at all in our configuration

locksmithctl reboot
Error initializing etcd client: 501: All the given peers are not reachable (Tried to connect to each peer twice and failed) [0]

In this case, the  update-window unit should just call a simple reboot?

**Comment by xueshanf** [comment] 2015-02-05 13:21
Okay now the locksmithctl supports endpoint so  workers can connect to the cluster etcd when etcd isn't running on local. I will add that to configuration. 
To improve maintenance window timer job to make sure all system get upgraded  when using locksmith is indeed more desirable. Thanks for the PR.

**Comment by crawford** [comment] 2015-02-05 18:46
locksmith should probably support a new "window" reboot strategy.

**Comment by xueshanf** [comment] 2015-02-05 21:39
While at it, I think there is a case that in the same cluster,  isolated etcd servers and workers may use different number of concurrent reboot locks. Also, does lock has TTL? What happens to the old lock(s) when machines do not reboot happily and has to be replaced by a new instance?

**Comment by crawford** [comment] 2015-02-05 22:23
Locks do not have a TTL. If the machine fails to release the lock, no other machines in the cluster will update. This is by design.

**Comment by ryneeverett** [comment] 2015-06-20 19:41
Shouldn't #446 have closed this?

**Comment by ElijahCaine** [comment] 2017-01-09 19:15
Closing due to inactivity.

**Closed by ElijahCaine** 2017-01-09 19:15 UTC
Labels: help-wanted, kind/enhancement
